server:
  port: 8888
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aws?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: root
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
winter-aws:
  access-key: ${MINIO-ACCESSKEY:zsqyyds}
  endpoint: ${MINIO-ENDPOINT:http://127.0.0.1:9886}
  secret-key: ${MINIO-ACCESSSECRET:zsqyyds123456789}
  bucket: ${MINIO-BUCKET:minio-springboot}
  path-style-access: true
  region: ap-east-1